apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abhi-pvc
  namespace: abhishek
spec:
  storageClassName: azurefile
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

