apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: abhishek
  labels:
    communication: stop
spec:
  containers:
  - image: nginx
    name: nginx-cont
    ports:
    - containerPort: 80  