apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: abhishek
spec:
  containers:
  - name: nginx-cont
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: volume-cont
      mountPath: /usr/share/nginx/html
      readOnly: false
  volumes:
  - name: volume-cont
    persistentVolumeClaim:
      claimName: abhi-pvc
    
