apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage1857abhishek
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=077
parameters:
  skuName: Standard_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate  