apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-pvc
  namespace: abhishek
  labels:
    type: podpvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: podpv
  storageClassName: abhishek2001mishra9989