apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod-pv
  namespace: abhishek
  labels:
    type: podpv
spec:
  azureFile:
    secretName: abhishek-secret
    shareName: abhishek-share
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: abhishek2001mishra9989
  