apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: abhishek
  labels:
    env: prod
spec:
  containers:
  - name: cont-nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-pod-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-pod-volume
    persistentVolumeClaim:
      claimName: pod-pvc