apiVersion: v1
kind: Pod
metadata:
  name: multi-layer-pod
  namespace: abhishek
spec:
  containers:
  - image: nginx
    name: nginx-pod
    ports: 
    - containerPort: 80
  - image: linuxserver/firefox
    name: firefox
    ports:
    - containerPort: 3000
